### ISSUE TITLE
Do not hot, and manually refresh the page after each change

### ISSUE THREAD

**Issue by 841660202** [kkltmoyu/NightPost#1]
Do not hot, and manually refresh the page after each change,.Check webpack.config.js
devServer: {
        port: 7000,
        hot: true,
        historyApiFallback: true,
        publicPath: "",
        stats: {
            colors: true
        },
        plugins: [
            new webpack.HotModuleReplacementPlugin()
        ]
    }
but it can work well,how to solve？

**Comment by 841660202** [comment]
you loss inline:true in this,

**Comment by kkltmoyu** [comment]
Thanks for your advice.I have fixed it ^_^

**Comment by kkltmoyu** [comment]
Thanks for your advice.I have fixed it ^_^
