### ISSUE TITLE
为什么是用HashRouter？如果用BrowserRouter的话，应该怎么写呢？

### ISSUE THREAD

**Issue by chj-damon** [kkltmoyu/NightPost#2]
我用browserRouter不知道express该怎么写。总是实现不了效果。

**Comment by kkltmoyu** [comment]
http://www.cnblogs.com/erduyang/p/6757788.html
除了这个，我记着我当初查这个问题的时候，还有人说要web服务器配置，比如nginx，但是我并没有试过
