### ISSUE TITLE
前端如何调取后端的函数？

### ISSUE THREAD

**Issue by wuxxx** [kkltmoyu/NightPost#3]
本人刚刚接触React和Express，拜读大神代码，有一点疑问想请教一下：app中保存的是前端代码，用react全家桶实现；server中保存的是后端代码，用express实现的restful api。那么在前端中，如何调用后端的函数呢？
本人也在做一个类似的上手练习，但是苦苦不知道如何在前端调用后端函数，请大神给予讲解或者博客链接。

**Comment by kkltmoyu** [comment]
@wuxxx  不知你曾经有没有做过后端的controller层，准确说前后端通信不是调用与被调用的关系。前后端通信一般都是通过ajax实现的，在我这个工程里用的是fetch而已，也是基于ajax的。具体到我这个项目中就是前端innerAction.js这个文件发出请求，后端server里index.js这个文件根据不同的映射地址对前端响应进行处理。这个机制与React或者Express本身无任何关系，用其他框架也是这么个过程。可以去百度下ajax的demo。再有问题给我留言吧

**Comment by wuxxx** [comment]
@kkltmoyu 这样实现的话，是不是需要分别开启后端服务和前端服务，然后前端通过fetch来与后端通信？

**Comment by kkltmoyu** [comment]
@wuxxx 对
